name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: test
        run: cargo test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Rust
        run: rustup update stable
      - name: Setup parquet files
        run: |
          apt update && apt install python3-pip python3-venv -y -q
          python3 -m venv venv
          venv/bin/pip install pip --upgrade
          venv/bin/pip install pyarrow==3
          venv/bin/python parquet_integration/write_parquet.py
      - uses: Swatinem/rust-cache@v1
      - name: Install tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run coverage
        run: |
          cargo tarpaulin --features cache_aligned --ignore-tests --out Xml
          cargo tarpaulin --features full --ignore-tests --out Xml
      - name: Report coverage
        continue-on-error: true
        run: bash <(curl -s https://codecov.io/bash)
